- package-lock.json
- package.json
- src/api/feed.js
- src/components/AppShell.vue
- src/components/modal/UploadGuideModal.vue
- src/features/feed/components/FeedUploadModal.vue
- 피드 등록 모달 구현
- 이미지, 동영상 등록 모달에서 이미지 업로드 
- 이미지 순서 변경 가능, hover시 삭제버튼 활성화되서 삭제 가능하게 구현
- 피드 내용 입력후 피드 업로드 버튼으로 피드 업로드
- <img width="400" alt="image" src="https://github.com/user-attachments/assets/2e0319c4-c274-4da0-bd26-f7ae00d6ff0c" />
> [FE] CAT-183 피드 등록 모달 구현

- package-lock.json
- package.json
- src/api/feed.js
- src/components/AppShell.vue
- src/composable/usePagination.js
- src/features/feed/components/FeedActions.vue
- src/features/feed/components/FeedCard.vue
- src/features/feed/components/FeedCarousel.vue
- src/features/feed/components/FeedCommentPreview.vue
- src/features/feed/components/FeedHeader.vue
- src/features/feed/components/FeedUploadModal.vue
- src/features/feed/router.js
- src/features/feed/views/FeedDetailPage.vue
- src/features/feed/views/FeedListPage.vue
- src/router/index.js
- 피드 목록 조회 페이지 구현
- 피드 목록 조회 페이지 구현
> [FE] CAT-181 피드 목록 조회 페이지 구현

- src/components/AppShell.vue
- src/components/modal/UploadGuideModal.vue
- src/features/feed/components/FeedActions.vue
- src/features/feed/components/FeedCard.vue
- src/features/feed/components/FeedCarousel.vue
- src/features/feed/components/FeedCommentPreview.vue
- src/features/feed/views/FeedListPage.vue
- 피드 등록 모달 피드 리스트 스타일 수정
- 피드 등록 모달 피드 리스트 스타일 수정
- DetailView로 라우팅
> [FE] CAT-198 피드 등록 모달 피드 리스트 스타일 수정

- src/api/feed.js
- src/features/feed/views/FeedDetailPage.vue
- src/features/feed/views/FeedListPage.vue
- 피드 상세 조회 모달 구현
- 피드 상세 조회 모달 구현
- 댓글 조회 추가 필요
- 좋아요 버튼에 api 연동 필요
> [FE] CAT-182 피드 상세 조회 모달 구현

- src/components/CommentSection.vue
- src/features/feed/views/FeedDetailPage.vue
- 댓글 components 구현
- 댓글 components 구현
- components에 CommentSection 추가
- 백엔등 연동 x
- 백엔드 연동
> Cat 191 fe 피드 댓글 components

- src/components/AppShell.vue
- src/features/feed/views/FeedListPage.vue
- src/stores/feedRefreshStore.js
- 피드 기능 버그 수정
- alert toast로 수정
- 피드 업로드시 피드 목록 바로 반영 안되는 버그 수정
- 다른 페이지에서 피드 업로드시 피드 목록 페이지로 route 처리
> [FE] Cat 209 fe 피드 기능 버그 수정

- src/api/comment.js
- src/components/CommentSection.vue
- src/features/feed/views/FeedDetailPage.vue
> CAT-208 댓글 컴포넌트 백엔드 연동

- src/components/AppShell.vue
> [BE] feat: CAT-220 버그수정

- src/api/feed.js
- src/features/feed/components/FeedCard.vue
- src/features/feed/views/FeedDetailPage.vue
> [FE] CAT-221 fe 피드 삭제 api 연동

- src/api/feed.js
- src/components/AppShell.vue
- src/components/modal/UploadGuideModal.vue
- src/features/feed/components/FeedCard.vue
- src/features/feed/components/FeedCarousel.vue
- src/features/feed/components/FeedUploadModal.vue
- src/features/feed/views/FeedDetailPage.vue
> Cat 224 fe 피드 수정 모달 구현

- index.html
- src/components/ShareDropdown.vue
- src/features/feed/components/FeedActions.vue
- src/features/feed/components/FeedCard.vue
- src/features/feed/views/FeedDetailPage.vue
- src/features/game/views/GameRanking.vue
- 공유 드롭다운 컴포넌트 생성
- 피드 공유 기능 추가
- 게임 공유 기능 추가
> [FE] CAT-184 fe 피드, 게임 공유 기능 추가

- src/api/member.js
- src/components/modal/BasicModal.vue
- src/features/member/components/DeleteMemModal.vue
- src/features/member/components/MemberInfoContent.vue
- src/features/member/components/RedButton.vue
- src/router/index.js
- src/stores/auth.js
> feat: 회원 탈퇴

- src/api/feed.js
- src/composable/usePagination.js
- src/router/index.js
> fix: 피드 리스트 비회원도 조회 가능하게 수정

- src/features/member/views/SignupExtraView.vue
🧩 트러블슈팅 이슈 요약: 소셜 로그인 후 추가 정보 입력 페이지에서 사용자 정보 미표시
🔍 문제 상황
구글/네이버/카카오 소셜 로그인 후 SignupExtraView.vue에서 name, contactNumber 등의 값이 표시되지 않음
콘솔/네트워크 상에서 에러는 없지만, 사용자 정보가 비어 있음
URL 쿼리 파라미터 (email, social)는 정상적으로 전달되고 있음
⚠️ 원인 분석
onMounted() 내부에서 getTempMemberInfo()를 호출했으나 startLoading()만 있고 API 요청 자체가 누락되었거나
getTempMemberInfo()는 호출되었지만 API 응답값에서 받은 contactNumber가 하이픈 포함(010-1234-5678)으로 들어와 추후 처리에 영향을 주었음
또는 초기에는 submitSignup()을 onMounted 내부에 잘못 정의해서 실제 동작을 막았던 구조적 문제도 있었음
🛠️ 해결 방법
onMounted() 내부에서 getTempMemberInfo(email, social)를 명확히 호출하여 임시 회원 정보 불러옴
받아온 값 중 contactNumber는 .replace(/-/g, '')로 하이픈 제거하여 일관된 포맷으로 상태 저장
ts
복사
편집
contactNumber.value = data.contactNumber.replace(/-/g, '');
submitSignup()은 onMounted 밖으로 이동하여 동작 오류 방지
useLoadingBar.js의 startLoading()과 stopLoading()을 onMounted()와 …
> fix: 소셜 로그인 후 추가 정보 입력 페이지에서 사용자 정보 미표시

- src/features/profile/views/ProfileEditView.vue
> feat: AWS S3 업로드 기능 구현(프로필 수정 시)

- src/components/CommentSection.vue
- src/features/block/components/BlockList.vue
> CAT-240 기능 수정

- src/api/feed.js
- src/api/like.js
- src/components/layout/SidebarMainLayout.vue
- src/composable/useInfiniteScroll.js
- src/features/feed/views/FeedListPage.vue
> Cat 230 fe 피드 목록 조회 무한 스크롤 적용

- src/components/CommentSection.vue
- src/features/block/components/BlockList.vue
- src/features/profile/components/ProfileHeader.vue
댓글에서 유저아이디 클릭 시 해당 유저 프로필로 이동
타 유저 프로필에 차단 기능 추가 이미 차단한 유저 면 차단해제
차단 목록에서 유저아이디 클릭시 유저 프로필로 이동
> CAT-259 기능 수정

- src/api/feed.js
- src/api/follow.js
- src/api/jjure.js
- src/components/AppShell.vue
- src/features/follow/components/FollowModal.vue
- src/features/notification/components/NotificationItem.vue
- src/features/notification/components/NotificationList.vue
- src/features/notification/components/NotificationModal.vue
- src/features/profile/components/OtherThumbnailList.vue
- initialFollowing 상태를 담아서 notiDTO 구성하기
> Cat 254 fe 디테일 수정

- src/features/feed/components/FeedCard.vue
- src/features/feed/components/FeedHeader.vue
> Cat 261 fe 피드 닉네임에 프로필 연결

- src/components/CommentSection.vue
- src/features/feed/views/FeedListPage.vue
피드 스크롤바 삭제
피드 목록 스크롤 화면 가장 위로 올리는 버튼 추가
댓글 영역 스크롤바 삭제
> Cat 262 fe 피드 스타일 수정

- src/components/EditDeleteDropdown.vue
- src/components/ShareDropdown.vue
피드 헤더 공유 드롭다운 버그 수정
수정삭제 드롭다운 아이콘 안보이는 버그 수정
공유 드롭다운 위치 수정
> Cat 263 fe 피드 헤더 공유 드롭다운 버그 수정

- src/features/member/components/Input.vue
- src/features/member/views/SignupExtraView.vue
- src/features/profile/components/CatFormModal.vue
- src/features/profile/views/ProfileEditView.vue
* 회원 가입 시 고양이 등록 기능 구현
* 프로필 수정 시 저장 오류 해결
> feat: 회원가입 시 고양이 등록 기능 구현
